

SELECT S.First_Name, S.Last_Name, S.CWID, COUNT(S.CWID) AS NO_OF_CLASSES
FROM STUDENT AS S
LEFT JOIN STUDENT_TAKES_COURSE ON STUDENT_TAKES_COURSE.CWID = S.CWID
GROUP BY S.CWID, S.First_NAME, S.LAST_NAME;



SELECT P.First_Name, P.Last_Name, P.Employee_ID, COUNT(P.Employee_ID) AS NO_CLASSES_TEACHING
FROM PROFESSOR AS P
LEFT JOIN COURSE_SECTION ON COURSE_SECTION.Employee_ID = P.Employee_ID
GROUP BY P.Employee_ID, P.First_NAME, P.LAST_NAME;
